### ISSUE TITLE
Choosing manually a field region for the decontamination algorithm

### ISSUE THREAD

**Issue by mzarricuetap** [asteca/ASteCA#548]
Greetings Gabriel, hope everything is fine

I'm Matias Zarricueta Plaza, a PhD student at the Universidad de La Serena. I'm currently working with Mr. Alexandre Roman Lopes, who has already use your code a few years ago in its version 0.2.3 for studying two high-density clumps in RCW 95 complex. My professor told me that you could manually select the field region in a separate file that was given as input to the program, which was especially useful in crowding and high extinction environments. Now, I'm using the version 0.4.3 to study some scarcely populated open clusters under high extinction levels, but I'm having some struggles with the output as the code does not find an adequate field region by itself. I have studied the asteca.ini file and the only thing I have found is that you can manually define the number of regions to use and you can give a number to the stellar density of the field, which in principle is not a problem since I could determine it in some other way. However, I have been left curious about this file, since I would like to automate the process to apply it to several other clusters and I would like to do it by means of this field definition file. I would like to know if it is possible to define such a file, and if so, where I should add the input. I don't want to use an earlier version of the code as using parallax/proper motions for membership determinations is an outstanding improve to the code.

Any comment will de surely helpful. Thanks for taking the time of reading this. I'll be attentive to your response. 

Have a very nice week!

Best regards,

Matías

**Comment by Gabriel-p** [comment]
Hi Matias,

as far as I can remember there was never the possibility to provide a separate file for the field region. With sparsely populated and very contaminated clusters the estimation of an average field region is a challenge. Since this parameter is mainly used to estimate the limiting radius (`r_cl` in AsteCA), you could also define this value manually.

If you need some help with the region(s) you are studying feel free to contact me at  gabrielperren [at] gmail.com. También podemos hablar en español :)

Saludos
