### ISSUE TITLE
Module 'numpy' has no attribute 'warnings' on Python 3.11 and Numpy 1.24.2

### ISSUE THREAD

**Issue by itsluquis** [asteca/ASteCA#549]
Hello!

I have the following problem on the first run of ASteCA, using the develop branch and the master branch.

<img width="1215" alt="image" src="https://user-images.githubusercontent.com/51384279/218294635-e448a0d8-5742-4f32-87ee-d8cdf63fbbe9.png">

I'm using Python 3.11.0 and Numpy 1.24.2.

Thanks!

**Comment by Gabriel-p** [comment]
Hi, the develop branch is not the finished product and should not be used as it is unstable. And even the 'master' branch (ie: the latest release) is not tested with the latest version of Python, that's why the instructions mention which Python version you should use: https://asteca.readthedocs.io/en/latest/install.html
